# Generated by Django 3.2 on 2023-01-29 23:27

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=8, prefix='', primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('taught_by', models.CharField(max_length=20, verbose_name='Taught by')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('how_long', models.SmallIntegerField(default=90, verbose_name='How long (minutes)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=8, prefix='', primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('events', models.ManyToManyField(blank=True, related_name='event_participants', to='register_events.Event', verbose_name='Events')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
    ]
