# Generated by Django 3.2 on 2023-01-26 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register_events', '0002_auto_20230125_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='birth_date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='how_long',
            field=models.SmallIntegerField(default=90, verbose_name='How long (minutes)'),
        ),
    ]
